### ISSUE TITLE
Is there anyway to add a threshold for motion alert?

### ISSUE THREAD

**Issue by gl-lamhnguyen** [KristopherKubicki/smartapp-turn-off-with-motion#1]
Like if alert threshold is >=5, the workflow is trigger...

Great app, I also use the Simulated motion app from you, but I wonder if there's a solution for my dilemma: I have a IP cam in the kitchen and sometimes if I'm around the area, I want the motion detector to turn off (like what your app does). However in case it isn't me in the kitchen, I need motion detector to stay on.

**Comment by KristopherKubicki** [comment]
Hey Lam - the way I know other people solve this is that they will make the app enabled/disabled with a switch (which I could add if you're interested).  Alternatively, making the app work in a certain mode or not, which it already does now.

**Comment by gl-lamhnguyen** [comment]
Thanks @KristopherKubicki, I've successfully modified your code to add a timer and a threshold for alert. It's working great for me. Code is from my other GH account: https://github.com/casper-gh/smartapp-turn-off-with-motion-with-threshold/

Much appreciated for your foundation code.
